language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
script:
  - "./gradlew clean :app:assembleRelease"
before_install:
  - chmod +x gradlew
install:
  - echo y | sdkmanager "ndk;21.0.6113669"
  - echo y | sdkmanager "cmake;3.6.4111459"
before_deploy:
  - export APP_VERSION=$(./gradlew :app:printVersionName)
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/app*release*.apk
  file_glob: true
  name: "$APP_VERSION"
  tag_name: "$APP_VERSION"
  overwrite: true
  skip_cleanup: true
  on:
    repo: mx0c/Android-BLE-Monitor
    branch: master
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
