language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
before_install:
- chmod +x gradlew
install:
- echo y | sdkmanager "ndk;21.0.6113669"
- echo y | sdkmanager "cmake;3.6.4111459"
deploy:
  provider: releases
  api_key:
    secure: U4oJ11ijemhf6Ru3rLPJFjJny996ZTPRgEXff7/eWsUNlH9dMvzxXWXTzPQjGrhFaONddv6z8P66VY5Wd5snobIr1hE4GqiY4QJu0Oa0VTqLqlxT//GE2QncdrqmD9UccyE/ANQY5ghEbFdRlWuqHyQ7z+YZX6dCQCHiLwtUMWgLPGwEXh95hkqZyvwci+oXyQeiuH2w/LoPUeaF1RZES/h6URiGZG/47y+q3Sg9CHDlwMhw9Y7wV1skg0nXAdt9mIyE5jcgaLKAhwRwJlywMXquMSCbjfN+oqCgmV4D3v+3RxjQS285hf4CK6fRkSm3Lh/xBHPvBJ5RnF5A0q+M3WOzkeeLCrBp1fICiyRqBZE8S/Qd9qUms6y489EnQLuwgNSXbJiJ0HbJdJ5tFy63S3Q/ZuI2fuZFobO2bCOMNJmU/PayliP+B0xgCSB1TvggsTsw2Bv7060qrdY59kMi6hXHKz5tSsAN9JzVgZU/+UtsEU61oihhXyoiU8IMa9cRPWysB2hhusH1PE+/3AqeYnMMPsYdfUZ+y3pmEVxloK1IU7TlPY9/M1k4LIFL/6k7a+/A3onHNiGJANUC/bq6TnEDJz/kMkHFztKwipsWgqD1owey5lKEUTYreoGQqlfJKIh2ioyhtmrNfUOrVJOWDsE3POuT9jNAvZVnQGMbN2k=
  file: AndroidBLEMonitor/build/outputs/apk/BLEM*release*.apk
  file_glob: "true"
  on:
    repo: mx0c/Android-BLE-Monitor
    branch: master
  skip_cleanup: 'true'
after_success:
- sh set_tags.sh
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
