language: android
sudo: required
jdk: oraclejdk8
android: 
   components:
      - tools
      - platform-tools
      - tools
      - build-tools-29.0.3
      - android-29
      - extra-android-m2repository
script:
    - ./gradlew build --stacktrace
before_install:
 - chmod +x gradlew
install:
 - echo y | sdkmanager "ndk;21.0.6113669"
 - echo y | sdkmanager "cmake;3.6.4111459"